// Generated by gencpp from file argus_msgs/ImageFiducialDetections.msg
// DO NOT EDIT!


#ifndef ARGUS_MSGS_MESSAGE_IMAGEFIDUCIALDETECTIONS_H
#define ARGUS_MSGS_MESSAGE_IMAGEFIDUCIALDETECTIONS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <argus_msgs/FiducialDetection.h>

namespace argus_msgs
{
template <class ContainerAllocator>
struct ImageFiducialDetections_
{
  typedef ImageFiducialDetections_<ContainerAllocator> Type;

  ImageFiducialDetections_()
    : header()
    , detections()  {
    }
  ImageFiducialDetections_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , detections(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::argus_msgs::FiducialDetection_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::argus_msgs::FiducialDetection_<ContainerAllocator> >::other >  _detections_type;
  _detections_type detections;





  typedef boost::shared_ptr< ::argus_msgs::ImageFiducialDetections_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::argus_msgs::ImageFiducialDetections_<ContainerAllocator> const> ConstPtr;

}; // struct ImageFiducialDetections_

typedef ::argus_msgs::ImageFiducialDetections_<std::allocator<void> > ImageFiducialDetections;

typedef boost::shared_ptr< ::argus_msgs::ImageFiducialDetections > ImageFiducialDetectionsPtr;
typedef boost::shared_ptr< ::argus_msgs::ImageFiducialDetections const> ImageFiducialDetectionsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::argus_msgs::ImageFiducialDetections_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::argus_msgs::ImageFiducialDetections_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace argus_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'argus_msgs': ['/home/jrv/Research/RoboticArcitecture/abb_experimental_ws/src/argus_utils/argus_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::argus_msgs::ImageFiducialDetections_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::argus_msgs::ImageFiducialDetections_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::argus_msgs::ImageFiducialDetections_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::argus_msgs::ImageFiducialDetections_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::argus_msgs::ImageFiducialDetections_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::argus_msgs::ImageFiducialDetections_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::argus_msgs::ImageFiducialDetections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f314965852957bf2ee56e7d38c9d340";
  }

  static const char* value(const ::argus_msgs::ImageFiducialDetections_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f314965852957bfULL;
  static const uint64_t static_value2 = 0x2ee56e7d38c9d340ULL;
};

template<class ContainerAllocator>
struct DataType< ::argus_msgs::ImageFiducialDetections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "argus_msgs/ImageFiducialDetections";
  }

  static const char* value(const ::argus_msgs::ImageFiducialDetections_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::argus_msgs::ImageFiducialDetections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Represents a set of fiducial detections from a single image\n\
# Timestamp and frame_id are from source image\n\
std_msgs/Header header\n\
\n\
# Detections found in the image\n\
FiducialDetection[] detections\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: argus_msgs/FiducialDetection\n\
# The name of this fiducial\n\
string name\n\
\n\
# Whether the points are undistorted\n\
bool undistorted\n\
\n\
# Whether the points are in normalized image coordinates\n\
bool normalized\n\
\n\
# The detected points\n\
Point2D[] points\n\
\n\
================================================================================\n\
MSG: argus_msgs/Point2D\n\
float64 x\n\
float64 y\n\
";
  }

  static const char* value(const ::argus_msgs::ImageFiducialDetections_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::argus_msgs::ImageFiducialDetections_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.detections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImageFiducialDetections_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::argus_msgs::ImageFiducialDetections_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::argus_msgs::ImageFiducialDetections_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "detections[]" << std::endl;
    for (size_t i = 0; i < v.detections.size(); ++i)
    {
      s << indent << "  detections[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::argus_msgs::FiducialDetection_<ContainerAllocator> >::stream(s, indent + "    ", v.detections[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARGUS_MSGS_MESSAGE_IMAGEFIDUCIALDETECTIONS_H
